name: naps_flutter
description: "A Flutter SDK for integrating NAPS SUNMI P2 payment terminals using the M2M TLV protocol via TCP/IP and Serial."
version: 2.1.0
homepage: https://github.com/p-Osteen/flutter_naps
repository: https://github.com/p-Osteen/flutter_naps
issue_tracker: https://github.com/p-Osteen/flutter_naps/issues

topics:
  - naps
  - payment
  - pos
  - sunmi
  - sdk

environment:
  sdk: ^3.11.5
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_libserialport: ^0.6.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter