const Map<String, String> kTagDescriptions = {
  '001': 'TM - Message Type',
  '002': 'MT - Payment Amount (Cents)',
  '003': 'NCAI - POS Identifier',
  '004': 'NS - Sequence Number',
  '005': 'NSA - Sequence Number to Cancel',
  '006': 'NHC - Cashier Station Number',
  '007': 'NCAR - Card Number (Masked)',
  '008': 'STAN - System Trace Audit Number',
  '009': 'NA - Bank Authorization Number',
  '010': 'DP - Printable Receipt Data',
  '011': 'CB - Barcode',
  '012': 'DE - Currency Code (504=MAD)',
  '013': 'CR - Response Code',
  '014': 'DA - Exchange Date (DDMMYYYY)',
  '015': 'HE - Exchange Time (HHMMSS)',
  '016': 'NPRT - Cardholder Name',
  '017': 'DAEX - Card Expiration Date (YYMM)',
  '018': 'DATR - Transaction Date (DDMMYYYY)',
  '019': 'HETR - Transaction Time (HHMMSS)',
  '020': 'TIDE - Ticket Requested',
  '021': 'TYPA - Payment Type',
  '040': 'EM - Card Entry Mode (CC/SC)',
};
